### ISSUE TITLE
bacasable session expirée 

### ISSUE THREAD

**Issue by LarcM7** [TrucsPES/vscode-mtess-frw-bacasable#1]
le popup de session expirée apparaît très rapidement (quelques secondes) dans le bac à sable

![Capture décran 2023-04-06 084126](https://user-images.githubusercontent.com/129791924/230381812-c34fbf89-74b2-45a1-8293-bfdbc18a8f65.png)

**Comment by LarcM7** [comment]
quick fix : mettre un r minuscule à "Render" dans la clé de config mtessFrwBacasable.url

**Comment by anisite** [comment]
L'erreur est au niveau de l'URL un bug empêche l'application de détecter le mode bac à sable si  le mot ’render’ est écrit autrement qu'en minuscules. Comme par exemple avec le R en majuscule ici :

![Screenshot_20230407-122715.png](https://user-images.githubusercontent.com/3194288/230643624-43dd19ea-db13-43ce-8ccc-b545d73d8b63.png)

Bug dans FRW et non pas l'outil bac à sable lui même.

**Comment by anisite** [comment]
https://devops700.itp.extra/700/_git/SPFS-FRW/pullrequest/10587?_a=overview
